### ISSUE TITLE
Can't even get my SP4 to boot into Live

### ISSUE THREAD

**Issue by RabidBurn** [jimdigriz/debian-mssp4#10]
I've been trying with devian 8.5.0 (both free and non-free) with Rufus to create the USB. I've tried GPT, and MBR, keeping it at FAT32...

Strange, because my SP4 will boot into a 2015 version of Ubuntu live that I happened to have lying around, but it won't boot into Debian or Kali...

Any suggestions?

**Comment by jimdigriz** [comment]
```
                                                                                  Sounds like Secure Boot (IIRC Ubuntu is signed), turn it off as per my destructions. Thanks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: RabidBurnSent: Wednesday, 10 August 2016 18:30To: jimdigriz/debian-mssp4Reply To: jimdigriz/debian-mssp4Subject: [jimdigriz/debian-mssp4] Can't even get my SP4 to boot into Live (#10)I've been trying with devian 8.5.0 (both free and non-free) with Rufus to create the USB. I've tried GPT, and MBR, keeping it at FAT32...
```

Strange, because my SP4 will boot into a 2015 version of Ubuntu live that I happened to have lying around, but it won't boot into Debian or Kali...

Any suggestions?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jimdigriz/debian-mssp4","title":"jimdigriz/debian-mssp4","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jimdigriz/debian-mssp4"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Can't even get my SP4 to boot into Live (#10)"}],"action":{"name":"View Issue","url":"https://github.com/jimdigriz/debian-mssp4/issues/10"}}}

**Comment by RabidBurn** [comment]
Thanks for the reply!

I just reconfirmed that secure boot is, in fact, off (and was before as well).

Still won't boot to Debian...

Any other ideas?

**Comment by RabidBurn** [comment]
Update: Not sure yet, but it might be that my SP4 doesn't like this USB stick. Trying a different one now, will update with results.

**Comment by RabidBurn** [comment]
Confirmed, the USB drive was the problem...

Sorry for wasting your time.
