### ISSUE TITLE
Type Cover stops working if I disconnect and reconnect while the system is up.

### ISSUE THREAD

**Issue by RabidBurn** [jimdigriz/debian-mssp4#11]
Not a big deal, just pointing it out.
Works flawlessly if the Type Cover is connected when the system boots, however, if I dc/rc it while the system is up, it stops responding until next reboot.

**Comment by jimdigriz** [comment]
You might find this is you typing cover failing. I had the same problem until I noticed that the problem also‎ occurred on boot too.Reconnecting the typing cover fixed the problem for me...on the 6th or so attempt....sometimes...but it got worse.Fortunately MS are great at replacements.‎Otherwise, if this is not it, my cover fine, the driver has been fine for ages. ‎ Are you running a stock kernel with patches or a Debian one? If you are running some other kernel, I cannot help.

**Comment by RabidBurn** [comment]
I don't think it's a Type Cover issue, it runs fine on Windows and during boot, plus, it's brand new.

I'm running Kali-rolling, but I did the kernel patch to version 4.6 as specified in your documentation.

I'm not super experienced with Linux, but it seems to me that should come out to about the same thing... Am I wrong?

**Comment by jimdigriz** [comment]
I too am getting this, its a recent kernel change as 'evtest' shows no events being generated

**Comment by Madwonk** [comment]
Probably kicking at a dead horse here, but...
After going through a similar process with Debian as you have here using a kernel based on yours from reddit, the type cover now responds to nothing. No gradual death, just instantateous. Can't get it to do anything or show up anywhere. It doesn't make sense to me, as the physical circuits should be designed in a way to prevent it, but is it in any way possible to kill the type cover because of software patches?

**Comment by Madwonk** [comment]
The rabbit hole goes deeper and deeper. Just tested the keyboard on a Surface RT, and it works fine. Tried vice versa (RT keyboard in SP4) and nothing happens. Is it possible to fry the internal circuits within the surface itself?

**Comment by jimdigriz** [comment]
It is always possible to kill any hardware because of patches, for example [Lenovo servers recently got bricked by a Win10 update](http://www.theregister.co.uk/2016/12/01/lenovo_block_microsoft_november_server_updte/) :)

Just RMA your typing cover, I have and found MS are outstanding on their returns policy.  Just state it no longer works do not mention Linux, it is not relevant.

**Comment by jimdigriz** [comment]
...RMA the SP4 its-self, just blat and reinstall Win10 from scratch using the factory recovery before you send it back.

**Comment by Madwonk** [comment]
Update: I didn't want to give up yet without trying some things, so I tried this: http://superuser.com/questions/1005006/surface-pro-4-keyboard-not-responding-and-leds-dont-work right here. Now it works! Very strange how that happened. Perhaps a problem within the UEFI prevented it from being initialized at the hardware level? I noticed around the same time the UEFI was becoming very slow, probably unrelated but thought it might be valuable to mention.

**Comment by jimdigriz** [comment]
Try adding the following to `/etc/udev/rules.d/90-local.rules`, it works for me:
````
# handle typing cover disconnects
# https://www.reddit.com/r/SurfaceLinux/comments/6axyer/working_sp4_typecover_plug_and_play/
ACTION=="add", SUBSYSTEM=="usb", ATTR{product}=="Surface Type Cover", RUN+="/sbin/modprobe -r i2c_hid && /sbin/modprobe i2c_hid"
````
