### ISSUE TITLE
Android camera drivers as linked rely on Intel Atom ISP

### ISSUE THREAD

**Issue by fridgecow** [jimdigriz/debian-mssp4#15]
Correct me if I'm wrong, but since the SP4 doesn't have an intel atom this could mean that the android drivers are basically not useful.

**Comment by jimdigriz** [comment]
The problem is not so much the hardware support for the camera its-self, the problem is how to get at it.  I think the camera sits behind the 'Sky Lake Imaging Unit' and there is no documentation that I could find last time I looked so that support for it could be put together (and then the cameras would be exposed):
```
alex@quatermain:~$ lspci
00:00.0 Host bridge: Intel Corporation Sky Lake Host Bridge/DRAM Registers (rev 09)
00:02.0 VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 0a)
00:05.0 Multimedia controller: Intel Corporation Sky Lake Imaging Unit (rev 01)
```

**Comment by fridgecow** [comment]
Hmmm. I believe your intuition is right. I'm a complete noob and so am way out of my depth, but I think it's safe to assume support for this will happen in time, as it doesn't look like the most obscure hardware.

Thanks for communicating this with me, I was attempting to compile the android drivers out-of-tree. Maybe put this info in the readme?
