### ISSUE TITLE
Can you detail a little bit about how to install in ubuntu?

### ISSUE THREAD

**Issue by magichowl** [jimdigriz/debian-mssp4#2]
I've installed ubuntu15.10 kernel 4.3 using the method of https://github.com/neoreeps/surface-pro-3.
When I tried your patches, I can't execute

```
xzcat ../linux-config-4.3/config.amd64_none_amd64.xz > .config
```

as I don't have directory of linux-config-4.3 and my kernel source is from git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git.

How to get it in ubuntu? Thanks.

**Comment by jimdigriz** [comment]
It is pretty clear in the instructions that they apply to a Debian 4.3 kernel and not the upstream git kernel HEAD of master which is currently 4.5-rc1.

I know Ubuntu is "kind of like Debian", but if you plan on using a different kernel and a different distribution, you have to understand you are under taking that task alone and exploring waters no one has documented or tried.

If you follow my linux-source-4.3 instructions on Ubuntu, with a _Ubuntu_ kernel, I might be able to help, otherwise good luck and I wish you the best.
