### ISSUE TITLE
Resume from sleep with 10s power button press

### ISSUE THREAD

**Issue by ofauchon** [jimdigriz/debian-mssp4#7]
Under Linux, when the tablet  goes sleep, you need to press power button for at least 10seconds to wake it up. 

Do you have the same behaviour ? 

How can we fix it so the tablet wakes up immediatly at power button pressing. 

Thx 
Olivier

**Comment by jimdigriz** [comment]
Yes I know about this, its in my instructions and has been four months.  The fix involves asking Microsoft to change the behaviour.

The real problem is that the Surface Pro (3 and 4, and probably the Book too) does not support real suspend, instead it uses connected standby (ACPI state S0ix), this is what is needed for 'suspend' to work, though this involves kernel and userspace work.

I want to work on the connected standby project, however I have to pay the bills...

**Comment by ofauchon** [comment]
Thanks for the details. 
More informations here: http://www.windowscentral.com/connected-standby-and-why-its-important-surface-pro-3
